completions: 1
image:
  repository: yuvipanda/jupyterhub-stress
  tag: v0.4.5
  pullPolicy: Always
resources: {}

hub:
  url: ""

users:
  count: 100
  startTime:
    max: 600
  runTime:
    min: 1800
    max: 3600
